# .github/workflows/check-sync.yml
name: Check Sync with Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  check-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch develop branch
        run: git fetch origin develop

      - name: Check if branch is up-to-date with develop
        run: |
          if ! git merge-base --is-ancestor origin/develop HEAD; then
            echo "Branch is not up to date with develop"
            exit 1
          fi
        shell: bash
